### ISSUE TITLE
Unexpected strict mode reserved word "let"

### ISSUE THREAD

**Issue by GuilhermeSpadaccia** [afucher/appsrvmon#7]
On Node.js version v0.12.7, I'm getting the following error:

let path_appserver = program.appserver || '';
^^^
SyntaxError: Unexpected strict mode reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by afucher** [comment]
@GuilhermeSpadaccia could you test with the latest version?   

```
npm update -g appsrvmon
```

**Comment by GuilhermeSpadaccia** [comment]
It's working now!!! \ o /

Ty.
